from __future__ import annotations

from collections import deque
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Any, Mapping, Sequence

import hashlib
import json


@dataclass(frozen=True)
class EvidenceRecord:
    """
    Immutable evidence record representing one observed
    EdgeResilience system state.

    This is a software/virtual-laboratory evidence artifact.
    It does not represent physical vehicle telemetry.
    """

    timestamp_utc: str
    event_id: str
    risk_state: Mapping[str, Any]
    telemetry: Mapping[str, Any]
    record_sha256: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class EvidenceBuffer:
    """
    Bounded local evidence buffer.

    The buffer is intentionally independent of the inherited
    Phase 5 experiment paths and datasets.

    It provides:
    - rolling local context
    - deterministic evidence records
    - event snapshots
    - bounded memory behavior
    """

    def __init__(
        self,
        max_records: int = 32,
    ) -> None:
        if max_records < 1:
            raise ValueError(
                "max_records must be at least 1."
            )

        self.max_records = int(max_records)

        self._records: deque[EvidenceRecord] = deque(
            maxlen=self.max_records
        )

    @property
    def size(self) -> int:
        return len(self._records)

    def clear(self) -> None:
        self._records.clear()

    def append(
        self,
        *,
        event_id: str,
        risk_state: Mapping[str, Any],
        telemetry: Mapping[str, Any],
        timestamp_utc: str | None = None,
    ) -> EvidenceRecord:
        """
        Add one deterministic evidence record.

        If timestamp_utc is omitted, the current UTC timestamp
        is generated by the local software runtime.
        """

        if not event_id:
            raise ValueError(
                "event_id must not be empty."
            )

        timestamp = (
            timestamp_utc
            if timestamp_utc is not None
            else datetime.now(
                timezone.utc
            ).isoformat()
        )

        canonical = {
            "timestamp_utc": timestamp,
            "event_id": event_id,
            "risk_state": _canonicalize(
                risk_state
            ),
            "telemetry": _canonicalize(
                telemetry
            ),
        }

        digest = sha256_canonical(
            canonical
        )

        record = EvidenceRecord(
            timestamp_utc=timestamp,
            event_id=event_id,
            risk_state=canonical[
                "risk_state"
            ],
            telemetry=canonical[
                "telemetry"
            ],
            record_sha256=digest,
        )

        self._records.append(record)

        return record

    def snapshot(
        self,
        *,
        event_id: str | None = None,
        include_all: bool = False,
    ) -> list[dict[str, Any]]:
        """
        Return a JSON-compatible snapshot.

        If event_id is provided, only records with that event ID
        are returned unless include_all is True.
        """

        records: Sequence[EvidenceRecord] = tuple(
            self._records
        )

        if (
            event_id is not None
            and not include_all
        ):
            records = tuple(
                record
                for record in records
                if record.event_id == event_id
            )

        return [
            record.to_dict()
            for record in records
        ]

    def verify(self) -> list[dict[str, Any]]:
        """
        Verify the digest of every currently buffered record.
        """

        results: list[dict[str, Any]] = []

        for record in self._records:
            canonical = {
                "timestamp_utc": record.timestamp_utc,
                "event_id": record.event_id,
                "risk_state": _canonicalize(
                    record.risk_state
                ),
                "telemetry": _canonicalize(
                    record.telemetry
                ),
            }

            calculated = sha256_canonical(
                canonical
            )

            results.append(
                {
                    "event_id": record.event_id,
                    "stored_sha256": record.record_sha256,
                    "calculated_sha256": calculated,
                    "valid": (
                        calculated
                        == record.record_sha256
                    ),
                }
            )

        return results


def _canonicalize(
    value: Any,
) -> Any:
    """
    Convert nested values into deterministic JSON-compatible
    structures.
    """

    if isinstance(value, Mapping):
        return {
            str(key): _canonicalize(
                nested
            )
            for key, nested in sorted(
                value.items(),
                key=lambda item: str(
                    item[0]
                ),
            )
        }

    if isinstance(value, (list, tuple)):
        return [
            _canonicalize(item)
            for item in value
        ]

    if isinstance(value, float):
        if value != value:
            return None

        if value in (
            float("inf"),
            float("-inf"),
        ):
            return None

        return float(value)

    if isinstance(value, (str, int, bool)):
        return value

    if value is None:
        return None

    return str(value)


def canonical_json(
    value: Mapping[str, Any],
) -> str:
    return json.dumps(
        _canonicalize(value),
        sort_keys=True,
        separators=(
            ",",
            ":",
        ),
        ensure_ascii=True,
    )


def sha256_canonical(
    value: Mapping[str, Any],
) -> str:
    payload = canonical_json(
        value
    ).encode("utf-8")

    return hashlib.sha256(
        payload
    ).hexdigest()


def build_event_id(
    *,
    scenario_id: str,
    event_sequence: int,
) -> str:
    if not scenario_id:
        raise ValueError(
            "scenario_id must not be empty."
        )

    if event_sequence < 0:
        raise ValueError(
            "event_sequence must not be negative."
        )

    return (
        f"{scenario_id}:"
        f"{int(event_sequence):06d}"
    )
